### PR TITLE
Removed 'make depend' and incorporated in 'make' for consistent behaviour

### PR DESCRIPTION
**Pull request by Yogaraj-Alamenda**

### CODE REVIEW

**Comment by stevelinsell** [comment]
This change will mean the engine specific error messages are generated on every make. This means a make depends step is no longer required. @ja1cul does this give better behaviour for you? Any feedback you have would be appreciated.

**Comment by ja1cul** [comment]
Yes.
These operations are very familier for me.
I'm waiting for your commit.

Thank you.

**Comment by Muffo** [comment]
Looks good to me :+1:

**Comment by agrandi** [comment]
Looks good to me :+1:

**Comment by stevelinsell** [comment]
+1 from me. We'll take the pull request into the baseline next week. It will become part of the release due the end of next week and should appear on master branch at that time.

**Comment by agrandi** [comment]
The code has been merged and it will be included in our next release.

Thanks!

**Pull request closed without merging**
